### ISSUE TITLE
Get the same pseudo element

### ISSUE THREAD

**Issue by robberfree** [greensock/GreenSock-JS#219]
when I use CSSRulePlugin.
for example,I only write 
```css
.navbar__nav__li::before
{
   content: "";
    position: absolute;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    background-color: #000000;
    z-index: -1;
}
```
in a .css file.
when  I want only to animate the first li of ul
```js
var rule = CSSRulePlugin.getRule(".navbar__nav__li:nth-child(1)::before");
TweenLite.to(rule, 1, { cssRule: { backgroundColor: "#ff0000"} });
```
I can't get the pseudo element rule.
can it possible?I read the code.now CSSRulePlugin just search the cssRule,not really detect computed style.

Thanks a lot.
